language: ruby
rvm: 2.1.3
sudo: false
cache: bundler
notifications:
    email: false


# bundler_args: --binstubs
env:
    global:
        - GIT_COMMITTER_NAME=ststgc
        - GIT_COMMITTER_EMAIL=ststgc@gmail.com
        - GIT_AUTHOR_NAME=ststgc
        - GIT_AUTHOR_EMAIL=ststgc@gmail.com
        - secure: "EIt7+OgYWBECKB/o9sIY5gaYelNix3Km+QMuGGuq4o2/9ehMIGwyenhmoMoCgOIXUmjoPgSnf2ebOCJizTSMsXTm3hRPQLupEuc7txGKhv+AYilJMe9kicpLz2Usp+xz8XYiG3VUBMQYjRTpt1lKTJNFfPRnNjUgTGjP8nS2PhA="
before_script:
    - git clone --quiet https://github.com/ststgc/baseline-grid.git build
    - pushd build
    - git checkout -b gh-pages
    - popd
    - npm install
script:
    - bundle exec grunt production
after_success:
    - cd build
    - git add -A
    - git commit -m 'Update'
    - '[ "$TRAVIS_BRANCH" == "master" ] && [ $GH_TOKEN ] && git push --quiet https://$GH_TOKEN@github.com/ststgc/baseline-grid.git gh-pages 2> /dev/null'
